#!/bin/bash

for i in $(seq 200)
do
    curl --location --request POST 'http://localhost:8090/data/1234' \
    --header 'Content-Type: application/json' \
    --data-raw '{
    "Metadata" : {
        "mod_id":"MOD1",
        "mac": "12AB12CD23"
    },
    "Time":{
        "date":"2022-10-21",
        "time":"11~12~09",
        "timeStamp":"2022/10/21 11:12:09",
        "weekday":"Friday",
        "season":"Fall"
    },
    "Location":{
        "ip":"138.4.195.144",
        "lat":40.4486,
        "lon":-3.71928,
        "str_lat":"40*4486",
        "str_lon":"-3*71928",
        "city":"Madrid",
        "region":"MD",
        "region_name":"Madrid",
        "country":"Spain",
        "country_code":"ES",
        "postal":28040,
        "timezone":"Europe/Madrid"
    },
    "HW":{
        "CPU_Usage":7.50963,
        "CPU_Temp":53.5,
        "RAM_Total":1917.6,
        "RAM_Usage":781.8,
        "RAM_Free":440.8,
        "DISK_Total":29.0,
        "DISK_Usage":40.0,
        "DISK_Free":17.0
    },
    "Weather":{
        "clouds":20.0,
        "humidity":89.0,
        "detailed_status":"few clouds",
        "visibility_distance":10000.0,
        "dewpoint":13.59,
        "uvi":0.71,
        "wind_speed":3.6,
        "wind_deg":160.0,
        "wind_gust":8.75,
        "press":1016.0,
        "temp":15.39,
        "temp_feels_like":15.31
    },
    "Sensors":[
        {
            "model":"Grove_-_VOC_and_eCO2_Gas_Sensor(SGP30)",
            "port":"Bus port",
            "value":403.0,
            "unit_of_measure":"http://www.ontology-of-units-of-measure.org/resource/om-2/partsPerMillion",
            "measure_property":"CO2eq",
            "Time":{
                "date":"2022-10-21",
                "time":"11~12~09",
                "timeStamp":"2022/10/21 11:12:09",
                "weekday":"Friday",
                "season":"Fall"
            },
            "Location":{
                "ip":"138.4.195.144",
                "lat":40.4486,
                "lon":-3.71928,
                "str_lat":"40*4486",
                "str_lon":"-3*71928",
                "city":"Madrid",
                "region":"MD",
                "region_name":"Madrid",
                "country":"Spain",
                "country_code":"ES",
                "postal":28040,
                "timezone":"Europe/Madrid"
            }
        },
        {
            "model":"Grove_-_VOC_and_eCO2_Gas_Sensor(SGP30)",
            "port":"Bus port",
            "value":0.0,
            "unit_of_measure":"https://bimerr.iot.linkeddata.es/def/weather#partsPerBillion",
            "measure_property":"TVOC(Total Volatile Organic Compounds)",
            "Time":{
                "date":"2022-10-21",
                "time":"11~12~09",
                "timeStamp":"2022/10/21 11:12:09",
                "weekday":"Friday",
                "season":"Fall"
            },
            "Location":{
                "ip":"138.4.195.144",
                "lat":40.4486,
                "lon":-3.71928,
                "str_lat":"40*4486",
                "str_lon":"-3*71928",
                "city":"Madrid",
                "region":"MD",
                "region_name":"Madrid",
                "country":"Spain",
                "country_code":"ES",
                "postal":28040,
                "timezone":"Europe/Madrid"
            }
        },
        {
            "model":"Grove_-_Light_Sensor_1*2",
            "port":"1",
            "value":343.0,
            "unit_of_measure":"http://www.ontology-of-units-of-measure.org/resource/om-2/candela",
            "measure_property":"LuminousIntensity",
            "Time":{
                "date":"2022-10-21",
                "time":"11~12~09",
                "timeStamp":"2022/10/21 11:12:09",
                "weekday":"Friday",
                "season":"Fall"
            },
            "Location":{
                "ip":"138.4.195.144",
                "lat":40.4486,
                "lon":-3.71928,
                "str_lat":"40*4486",
                "str_lon":"-3*71928",
                "city":"Madrid",
                "region":"MD",
                "region_name":"Madrid",
                "country":"Spain",
                "country_code":"ES",
                "postal":28040,
                "timezone":"Europe/Madrid"
            }
        },
        {
            "model":"Grove_-_Light_Sensor_1*2",
            "port":"1",
            "value":19.83,
            "unit_of_measure":"http://www.ontology-of-units-of-measure.org/resource/om-2/ohm",
            "measure_property":"LuminousResistance",
            "Time":{
                "date":"2022-10-21",
                "time":"11~12~09",
                "timeStamp":"2022/10/21 11:12:09",
                "weekday":"Friday",
                "season":"Fall"
            },
            "Location":{
                "ip":"138.4.195.144",
                "lat":40.4486,
                "lon":-3.71928,
                "str_lat":"40*4486",
                "str_lon":"-3*71928",
                "city":"Madrid",
                "region":"MD",
                "region_name":"Madrid",
                "country":"Spain",
                "country_code":"ES",
                "postal":28040,
                "timezone":"Europe/Madrid"
            }
        },
        {
            "model":"Grove_-_Temperature&Humidity_Sensor_Pro(DHT22)",
            "port":"4",
            "value":24.1,
            "unit_of_measure":"http://www.ontology-of-units-of-measure.org/resource/om-2/degreeCelsius",
            "measure_property":"Temperature",
            "Time":{
                "date":"2022-10-21",
                "time":"11~12~09",
                "timeStamp":"2022/10/21 11:12:09",
                "weekday":"Friday",
                "season":"Fall"
            },
            "Location":{
                "ip":"138.4.195.144",
                "lat":40.4486,
                "lon":-3.71928,
                "str_lat":"40*4486",
                "str_lon":"-3*71928",
                "city":"Madrid",
                "region":"MD",
                "region_name":"Madrid",
                "country":"Spain",
                "country_code":"ES",
                "postal":28040,
                "timezone":"Europe/Madrid"
            }
        },
        {
            "model":"Grove_-_Temperature&Humidity_Sensor_Pro(DHT22)",
            "port":"4",
            "value":51.6,
            "unit_of_measure":"http://www.ontology-of-units-of-measure.org/resource/om-2/percentage",
            "measure_property":"RelativeHumidity",
            "Time":{
                "date":"2022-10-21",
                "time":"11~12~09",
                "timeStamp":"2022/10/21 11:12:09",
                "weekday":"Friday",
                "season":"Fall"
            },
            "Location":{
                "ip":"138.4.195.144",
                "lat":40.4486,
                "lon":-3.71928,
                "str_lat":"40*4486",
                "str_lon":"-3*71928",
                "city":"Madrid",
                "region":"MD",
                "region_name":"Madrid",
                "country":"Spain",
                "country_code":"ES",
                "postal":28040,
                "timezone":"Europe/Madrid"
            }
        },
        {
            "model":"Grove_-_Loudness_Sensor",
            "port":"0",
            "value":41.87,
            "unit_of_measure":"http://www.ontology-of-units-of-measure.org/resource/om-2/decibel",
            "measure_property":"Loudness",
            "Time":{
                "date":"2022-10-21",
                "time":"11~12~09",
                "timeStamp":"2022/10/21 11:12:09",
                "weekday":"Friday",
                "season":"Fall"
            },
            "Location":{
                "ip":"138.4.195.144",
                "lat":40.4486,
                "lon":-3.71928,
                "str_lat":"40*4486",
                "str_lon":"-3*71928",
                "city":"Madrid",
                "region":"MD",
                "region_name":"Madrid",
                "country":"Spain",
                "country_code":"ES",
                "postal":28040,
                "timezone":"Europe/Madrid"
            }
        }
    ]
    }' 
done